dist: trusty

language: java
jdk:
  - oraclejdk8

services:
  - postgresql

addons:
  postgresql: "9.6"

before_install:
  - java -version
  - node -v
  - npm -v
  - google-chrome --version

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database "treeline-test";' -U postgres
  - npm run build
  - ./gradlew bootRun -Dspring.profiles.active=test | tee log.txt &
  - ./scripts/wait_for_log.sh log.txt "Started TreelineApplicationKt"

script:
  - npm run test-jsu
  - npm run test-e2e