language: java
jdk:
  - oraclejdk8

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - npm install

before_script:
  - psql -c 'create database treeline-test;' -U postgres

script:
  - npm run test-jsu