dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
      sources:
        - google-chrome
      packages:
        - google-chrome-stable

before_install:
  - npm i -g npm

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database "treeline-test";' -U postgres
  - ./mvnw spring-boot:run -Drun.profiles=test &
  - sleep 240

script:
  - npm run test-jsu
  - npm run test-e2e