language: java

node_js:
  - "4.3"

services:
  - postgresql

addons:
  postgresql: "9.5"

install:
  - npm install

before_script:
  - psql -c 'create database treeline-test;' -U postgres

script:
  - npm run test-jsu